name: code-qa
run-name: code-qa

on:
  push:

env:
  REPO_LINK: "git@github.com:EpitechPromo2027/B-OOP-400-NAN-4-1-arcade-baptiste.moreau.git"
  EXECUTABLES: "arcade"

jobs:
  build:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Program Compilation
        run: make

      - name: Binary Verification
        run: |
          IFS=','
          read -a arr <<< ${{ env.EXECUTABLES }}
          for exec in "${arr[@]}"
          do
              if [ ! -x $exec ]; then
                  exit 1
              fi
          done

  test:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Criterion Tests
        run: |
          make tests_run

  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.REPO_LINK }}
          ssh_private_key:
            ${{ secrets.MIRROR_KEY }}